config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  get 'password_resets/new'

  get 'password_resets/edit'

  get "order_products/index"

  get "order_products/show"

  get "order_products/new"

  get "sessions/new"
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "line_items/:id/add" => "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce" => "line_items#reduce_quantity", as: "line_item_reduce"
  resources :line_items
  resources :order_products
  resources :my_orders, only: [:index]
  resources :carts
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories
  resources :account_activations, only: :edit
  resources :products do
    resources :reviews
  end

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :products, except: :show
    resources :categories, except: :show
    resources :order_products
  end
end

app/views/layouts/admin/_footer.html.erb
<!-- /.content-wrapper-->
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © Your Website 2018</small>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <%= link_to t(".logo"),admin_users_path, class: "navbar-brand" %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <%= link_to(admin_users_path, class: "nav-link") do %>
          <i class="fa fa-fw fa-users"></i>
          <span  class="nav-link-text"><%= t ".users" %></span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <%= link_to(admin_products_path, class: "nav-link") do %>
          <i class="fa fa-fw fa-table"></i>
          <span  class="nav-link-text"><%= t ".products" %></span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <%= link_to(admin_categories_path, class: "nav-link") do %>
          <i class="fa fa-fw fa-list-ul"></i>
          <span  class="nav-link-text"><%= t ".categories" %></span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <%= link_to(admin_order_products_path, class: "nav-link") do %>
        <i class="fa fa-fw fa-shopping-cart"></i>
        <span  class="nav-link-text"><%= t ".orders" %></span>
        <% end %>
      </li>
    </ul>
    <!-- <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul> -->

    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="dropdown ">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag(current_user.image) %>
            <span class="username"><%= current_user.name %></span>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <i class="fa fa-fw fa-sign-out"></i>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin/application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/admin/shim" %>
  </head>
  <body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <%= render "layouts/admin/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="content-wrapper">
      <%= yield %>
      <%= render "layouts/admin/footer" %>
    </div>
  </body>
</html>