config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  get 'password_resets/new'

  get 'password_resets/edit'

  get "order_products/index"

  get "order_products/show"

  get "order_products/new"

  get "sessions/new"
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "line_items/:id/add" => "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce" => "line_items#reduce_quantity", as: "line_item_reduce"
  resources :line_items
  resources :order_products
  resources :my_orders, only: [:index]
  resources :carts
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories
  resources :account_activations, only: :edit
  resources :products do
    resources :reviews
  end

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :products, except: :show
    resources :categories, except: :show
    resources :order_products
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product product_id
    current_item = line_items.find_by_product_id product_id
    if current_item
      current_item.quantity += Settings.cart.quantity
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:total_price)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts/1
  # GET /carts/1.json
  def show; end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    if @cart.destroy
      session[:cart_id] = nil
      flash[:success] = t("carts.destroy.notice2")
    else
      flash[:danger] = t("carts.destroy.erro")
    end
    redirect_to products_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find_by id: params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch :cart, {}
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/views/carts/_cart.html.erb
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%"><%= t ".product" %></th>
        <th style="width:10%"><%= t ".price" %></th>
        <th style="width:8%"><%= t ".quantity" %></th>
        <th style="width:12%" class="text-center"><%= t ".subtotal" %></th>
        <th style="width:20%"></th>
        <th style="width:20%"></th>
      </tr>
    </thead>

    <tbody>
      <% cart.line_items.each do |line_item| %>
        <%= render "line_items/line_item", line_item: line_item, show_total: true %>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td><%= link_to t(".continue"), products_path, class: "btn btn-warning" %></td>
        <td><%= button_to t(".empty"), cart, class: "btn btn-success btn-block", :method => :delete, data: {:confirm => t(".confirm") } %></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong><%= t ".total" %><%= number_to_currency(cart.total_price) %></strong></td>
        <td><%= button_to t(".checkout"), new_order_product_path, class: "btn btn-success btn-block", :method => :get %></td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>
      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_line_items.html.erb
<%= form_for line_items.to_ary do |f| %>
  <tbody>
    <tr>
      <td data-th="Product">
        <div class="row">
          <div class="col-sm-3 hidden-xs"><%= link_to image_tag(f.product.image, :size => "100x100"), :size => "10x20", alt: t(".alt") %></div>
          <div class="col-sm-9">
            <h4 class="nomargin"><%= f.product.name %></h4>
            <p><%= f.product.description %></p>
          </div>
        </div>
      </td>
      <td data-th="Price"><%= number_to_currency(f.product.price) %></td>
      <td data-th="Quantity">
        <%= f.number_field :quantity %>
      </td>
      <td data-th="Subtotal" class="text-center"><%= number_to_currency(f.total_price) %></td>
      <td class="actions" data-th="">
        <%= link_to (submit_tag "update",  class: "btn btn-info btn-sm"), f, :method => :patch %>
        <%= link_to (submit_tag "delete", class: "btn btn-danger btn-sm"), "#",:method => :patch %>
      </td>
    </tr>
  </tbody>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<%= notice %>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container">
  <%= render @cart %>
</div>