config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  get 'password_resets/new'

  get 'password_resets/edit'

  get "order_products/index"

  get "order_products/show"

  get "order_products/new"

  get "sessions/new"
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "line_items/:id/add" => "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce" => "line_items#reduce_quantity", as: "line_item_reduce"
  resources :line_items
  resources :order_products
  resources :my_orders, only: [:index]
  resources :carts
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories
  resources :account_activations, only: :edit
  resources :products do
    resources :reviews
  end

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :products, except: :show
    resources :categories, except: :show
    resources :order_products
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items
  has_many :pictures, dependent: :destroy
  has_many :reviews, dependent: :destroy
  before_destroy :check_if_has_line_item
  ratyrate_rateable "quality"
  # , "original_score"
  mount_uploader :image, PictureUploader

  scope :search_by_name, lambda{|search|
    where("name LIKE ?", "%#{search}%") if search.present?
  }

  private

  def check_if_has_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, t("model.product.error"))
      return false
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :load_product, except: %i(index create new)
  before_action :load_all_category, only: %i(new edit show)

  def new
    @products = Product.new
  end

  def create
    @products = Product.new product_params
    if @products.save
      flash[:success] = t ".add_success"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def index
    @products = Product.search_by_name(params[:search]).paginate(page: params[:page],
      per_page: Settings.pag_max)
    @category = Category.find_by id: params[:category_id]
  end

  def edit; end

  def update
    if @products.update_attributes(product_params)
      flash[:success] = t ".updated"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    if @products.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".destroy_fail"
    end
    redirect_to admin_products_path
  end

  private

  def load_product
    @products = Product.find_by id: params[:id]
    return if @products
    flash[:danger] = t "cant_find_product"
    redirect_to root_url
  end

  def load_category
    unless params[:category].nil?
      @category = Category.find_by name: params[:category]
      return if @category
      render file: "public/404.html"
    end
  end

  def product_params
    params.require(:product).permit :name, :size, :price, :quantity, :description, :category_id, :image
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search_by_name(params[:search]).paginate(page: params[:page],
      per_page: Settings.product.pag_max)
    @cart = current_cart
  end

  def show
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t("products.show.mess")
    redirect_to root_url
  end

  def product_params
    params.require(:product).permit :name, :size, :price, :description, :category_id, :image, :quantity
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def show_image_for product
    image_tag(product.image.url, class: "img-responsive")
  end

  def bought_this_product_before?
    if logged_in?
      if (@ordered_list = current_user.orders.ids).present?
        @ordered_list.each do |item|
          @check = current_user.orders.find(item).order_details.find_by product_id: params[:id]
          break if @check.present?
        end
      end
      @check.present?
    else false
    end
  end
end

app/views/admin/products/_form.html.erb
<%= form_for(@products, url: yield(:url)) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <% if yield(:is_edit?) == "true" %>
    <div class="edit_form_image">
      <%= show_image_for @products %>
    </div>
  <% end %>
  <%= f.label :image %>
  <%= f.file_field :image  %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, class: "form-control", placeholder: "Name" %>

  <%= f.label :description %>
  <%= f.text_field :description, required: true, class: "form-control", placeholder: "Description" %>

  <%= f.label :price %>
  <%= f.number_field :price, required: true, class: "form-control", placeholder: "Price" %>

  <%= f.label :quantity %>
  <%= f.number_field :quantity, required: true, class: "form-control", placeholder: "Quantity" %>

  <%= f.label :size %>
  <%= f.text_field :size, required: true, class: "form-control", placeholder: "Size" %>

  <%= f.label :category_id %>
  <%= f.collection_select :category_id, @categories, :id, :name, {promt: t(".choose_cate")} %>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/products/_products.html.erb
<% @products.each do |p| %>
  <tr class="row_custom">
    <td class="cell_custom"><%= p.id %></td>
    <td class="cell_custom"><%= image_tag(p.image) %></td>
    <td class="cell_custom"><%= p.name %></td>
    <td class="cell_custom"><%= p.description %></td>
    <td class="cell_custom"><%= p.price %></td>
    <td class="cell_custom"><%= p.size %></td>
    <td class="cell_custom"><%= p.quantity %></td>
    <td class="cell_custom"><%= p.discount %></td>
    <td class="cell_custom"><%= p.category.name %></td>
    <td><%= link_to t("view.edit"),
      edit_admin_product_path(p), class: "btn btn-success"%>
    </td>
    <td><%= link_to t("view.delete"),
      [:admin, p], method: :delete, class: "btn btn-danger",
      data: {confirm: t("sure?")} %>
    </td>
  </tr>
<% end %>

app/views/admin/products/edit.html.erb
<% provide(:title, t(".edit")) %>
<% provide(:button_text, t(".update")) %>
<% provide(:is_edit?, "true") %>
<% provide(:url, admin_product_path) %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit Product</h1>
    <%= render "form" %>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide :title, t(".title") %>
<% provide :table, t(".table_product") %>
<% provide :add, t(".add_product") %>

<div class="container-fluid">
  <div class="card mb-3">
    <div class="card-header"><i class="fa fa-table"></i> <%= yield(:table) %></div>
    <div class="card-body">
      <div class="table-responsive">
        <div class="add_pd">
          <%= link_to yield(:add), new_admin_product_path, class: "btn btn-primary" %>
          <div class="search-bar">
            <%= form_tag admin_products_path, method: :get do %>
            <%= text_field_tag :search, params[:search], placeholder: t(".search") %>
            <% end %>
          </div>
        </div>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr class="row_custom header">
              <th class="cell_custom"><%= t "view.id" %></th>
              <th class="cell_custom"><%= t "view.image" %></th>
              <th class="cell_custom"><%= t "view.name" %></th>
              <th class="cell_custom"><%= t "view.description" %></th>
              <th class="cell_custom"><%= t "view.price" %></th>
              <th class="cell_custom"><%= t "view.size" %></th>
              <th class="cell_custom"><%= t "view.quantity" %></th>
              <th class="cell_custom"><%= t "view.discount" %></th>
              <th class="cell_custom"><%= t "view.category" %></th>
              <th colspan="2", class="cell_custom"><%= t "view.action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render "products" %>
          </tbody>
        </table>
        <div class="pag">
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide(:title, t(".add_product")) %>
<% provide(:button_text, t(".add_product")) %>
<% provide(:url, admin_products_path) %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Add Product</h1>
    <%= render "form" %>
  </div>
</div>